### PR TITLE
mrc-1243 pass language accept header to hintr

### PR DESCRIPTION
**Pull request by hillalex**
Pass the language header from the front-end through to hintr calls.

Contains commits from https://github.com/mrc-ide/hint/pull/215

### CODE REVIEW

**Comment by hillalex** [comment]
Hmm, I  merged master in here and now the build is failing because the cancel run tests are failing, I presume because the hintr changes aren't merged to master? Can they be?

**Comment by EmmaLRussell** [comment]
I think Rich still had some work to do on the cancel run branch, and needs PR review, but thought it was pretty much there.

**Comment by hillalex** [comment]
> I think Rich still had some work to do on the cancel run branch, and needs PR review, but thought it was pretty much there.

Unfortunately because the translations don't exist on that hintr branch, this is now blocked until that gets merged.

**Comment by EmmaLRussell** [comment]
Could reset the hintr branch to master then. I think there's just a backend integration test which could be changed to expect a 404 for now, and a front end test which could also expect a 404 rather than a 400. The actual cancel behaviour in the front end shouldn't be affected since it ignores errors, and in the backend the run would continue unaffected.

**Comment by hillalex** [comment]
This is now unblocked @EmmaLRussell

**Pull request merged**
