### PR TITLE
mrc-2223 add enter key event to create project input field 

### PR DESCRIPTION
**Pull request by carbowizzy**
Adds enter event to create project field. A user can create a new project when he/she press enter button.

Please describe your changes here

## Type of version change
_Delete as appropriate_

Minor

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by mwoodbri — COMMENTED** [review]
This all looks good and works well.

But not sure how it relates to mrc-2223? Doesn't appear to fix any accessibility issues described by the report attached to ticket.

**Comment by EmmaLRussell** [comment]
> This all looks good and works well.
> 
> But not sure how it relates to [mrc-2223](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2223)? Doesn't appear to fix any accessibility issues described by the report attached to ticket.



> This all looks good and works well.
> 
> But not sure how it relates to [mrc-2223](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2223)? Doesn't appear to fix any accessibility issues described by the report attached to ticket.

Just what I was about to say! Is this branch actually for a different ticket?

**Review by Nicolas-Dolan — APPROVED** [review]
Works well. Just need to update the versions.

**Comment by mwoodbri** [comment]
Another observation: there's a related ticket mrc-2156, which seems to suggest that consistent behaviour would be for enter button to select submit button, rather than to immediately submit the form. We need to decide which behaviour is preferred.

**Pull request closed without merging**
