### PR TITLE
mrc-2699 Add feedback to error report modal

### PR DESCRIPTION
**Pull request by EmmaLRussell**
## Description

This branch delays closure of the error report dialog while feedback is displayed to the user, whether that is a generic success message or a display of an error which occurred. The user then presses 'Close' to finally close the modal. 

## Type of version change
_Delete as appropriate_

Minor

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by Nicolas-Dolan — COMMENTED** [review]
I'm not sure how to test this. Could you provide instructions?

**Comment by EmmaLRussell** [comment]
> I'm not sure how to test this. Could you provide instructions?

To test the success feedback, just run it up locally and submit an error report from Online support | Report issues - it won't actually submit an error report to Teams when running locally. You should see the generic success  'report submitted' message.  

To test the error case, you'll need to sabotage it somehow, either by throwing an exception in the backend or just doctoring the url it's hitting in the root generateErrorReport action so the app returns a 404.

**Review by Nicolas-Dolan — APPROVED** [review]
Everything works as expected.

**Comment by EmmaLRussell** [comment]
I've changes the messages to refer to user's "request" rather than "report" since the menu item and dialog title is changing to "Troubleshooting request" [here](https://github.com/mrc-ide/hint/pull/593)

**Review by LekanAnni — APPROVED** [review]
LGTM

**Pull request merged**
