### PR TITLE
Mrc 3945 Fix project load issue

### PR DESCRIPTION
**Pull request by LekanAnni**
## Description

This PR adds test to the changes made in hintr regarding resourceUrl. Initial implementation does not allow null value, resource_url has must contain data. However, this causes validation issue when loading legacy projects. This is now fixed and tests are added to this effect.

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by EmmaLRussell — APPROVED** [review]
This works for me! I'm still not completely sure why this fixes it, since the methods had nullable parameters anyway. Did something else object to the default empty string, but was ok with nulls?

**Comment by LekanAnni** [comment]
> This works for me! I'm still not completely sure why this fixes it, since the methods had nullable parameters anyway. Did something else object to the default empty string, but was ok with nulls?

The error comes from the schema validation service. `name : string? = ""` does not handle null but empty response. In fact we should not be using snippets such as `name : string? = "" but name : string? = null`.

**Comment by EmmaLRussell** [comment]
> > This works for me! I'm still not completely sure why this fixes it, since the methods had nullable parameters anyway. Did something else object to the default empty string, but was ok with nulls?
> 
> The error comes from the schema validation service. `name : string? = ""` does not handle null but empty response. In fact we should not be using snippets such as `name : string? = "" but name : string? = null`.

Oh, when it's trying to create objects for that data class from the results from the db? (Not the hintr schema?)

**Comment by LekanAnni** [comment]
> > > This works for me! I'm still not completely sure why this fixes it, since the methods had nullable parameters anyway. Did something else object to the default empty string, but was ok with nulls?
> > 
> > 
> > The error comes from the schema validation service. `name : string? = ""` does not handle null but empty response. In fact we should not be using snippets such as `name : string? = "" but name : string? = null`.
> 
> Oh, when it's trying to create objects for that data class from the results from the db? (Not the hintr schema?)

No, the issue was from the schema, I initially thought I would be able to handle it in frontend using `name : string? = ""` but I then realised this does not handle nullable.

**Pull request merged**
