### PR TITLE
Mrc 1662 - Add project help text/explanation to Project view

### PR DESCRIPTION
**Pull request by carbowizzy**
explanation text and translations added to project view. The French is derived from google translate.

### CODE REVIEW

**Review by EmmaLRussell — APPROVED** [review]
Looks good. :+1:

**Comment by EmmaLRussell** [comment]
Looks good, but just needs conflicts fixing before merging. Not sure what's going on with Travis, but maybe just fix the conflicts to kick off a new build and see how that goes...

**Review by EmmaLRussell — CHANGES_REQUESTED** [review]
Sorry, I jumped the gun on approving - you'll have to check for this new text in the tests as well.

**Review by hillalex — APPROVED** [review]
Nice one :+1: . Just need to fix the conflict with master.

**Review by EmmaLRussell — APPROVED** [review]

**Pull request merged**
