### PR TITLE
Add licence

### PR DESCRIPTION
**Pull request by r-ash**
## Description

This adds a LICENCE file with standard MIT licence text

## Type of version change

None

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by richfitz — APPROVED** [review]

**Comment by r-ash** [comment]
> Nice, I think `MIT © Imperial College of Science, Technology and Medicine` would be sufficient since we have used the same in some projects.

Had a quick look at other LICENCE and LICENCE.md files in mrc-ide repo and I've updated this to match that format. I think we're using the full text in most places so let's go with that?

**Review by richfitz — APPROVED** [review]

**Comment by LekanAnni** [comment]
@r-ash this PR has failing tests.

**Comment by r-ash** [comment]
Thanks I think just some flakiness with failing test, should be good to go now

**Review by richfitz — APPROVED** [review]

**Review by LekanAnni — APPROVED** [review]
Nice 👍

**Pull request merged**
