### PR TITLE
mrc-2930 add register link to login page

### PR DESCRIPTION
**Pull request by LekanAnni**
## Description

This PR adds registration link to login page.

## Type of version change
_Delete as appropriate_

Minor 

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
LGTM. Could maybe avoid that awkward line break in the middle of the link just by adding a break before the link (see below)? Or alternatively could make the card a little wider. 
reqacc1
reqacc2

**Comment by LekanAnni** [comment]
> I am not sure how you managed to reduce the page to that level, I tried to replicate it but the minimum screen size on Firefox, chrome and safari still fits well.

Okay, I think the second screen is what you had like, right ?

**Review by Nicolas-Dolan — APPROVED** [review]

**Comment by EmmaLRussell** [comment]
> > I am not sure how you managed to reduce the page to that level, I tried to replicate it but the minimum screen size on Firefox, chrome and safari still fits well.
> 
> Okay, I think I misinterpreted your request, the second screen is what you had like, right ?

The second image was my suggestion to fix the issue with the first one. I was using Chrome on 100% zoom, nothing odd about settings I don't think.

**Review by EmmaLRussell — APPROVED** [review]
Thanks, looks good

**Pull request merged**
