### PR TITLE
mrc-2518 Move all file upload controls to Step 1

### PR DESCRIPTION
**Pull request by carbowizzy**
This PR is an epic consisting of mrc-2564 , mrc-2565 and mrc-2566. 

I am combining the above branches in this epic to encourage master is not broken if merged separately. This is a standalone feature for moving upload input fields in survey and program step(SAP) to baseline step. 

Unfortunately I merged this last branch mrc-2566 to this epic before approval as I thought it would make no sense to review it separately and also review this epic but alas I was wrong. 

The changes made to mrc-2566 are as follows:
1.  renaming of some steps and
2. validation of SAP upload on baseline step

This PR combines SAP and Baseline states, using both states together on Baseline step. I have implemented the following :

-	Moved SAP manage-file and logic to Baseline step
-	Modified root modules, alter “resetState” for Baseline and SAP to adjust to the new implementation. 
-	Added more validation to Baseline for SAP
-	Renamed step 1 and 2 to Upload inputs and Review inputs
-	Reused SAP actions/mutations in Baseline
-	Synchronised Baseline and SAP states validation in Baseline

## Type of version change
_Delete as appropriate_

 Minor

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by EmmaLRussell — COMMENTED** [review]
I don't believe this Epic branch is ready for review. If you recall, the mrc-2566 branch has not yet had an approval, and we agreed to re-open that for review, as that would be easier for reviewer than attempting to review the bits of this epic branch which had come from the latest ticket. 
https://github.com/mrc-ide/hint/pull/529
Was that not the case?

**Comment by carbowizzy** [comment]
> review

It was but I am struggling to revample the mrc-2518 properly. I think it won't be so tedious reviewing this epic since we have had some of them reviewed.

**Comment by EmmaLRussell** [comment]
> > review
> 
> It was but I am struggling to revample the [mrc-2566](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2566) properly. I think it won't be so tedious reviewing this epic since we have had some of them reviewed. The only bit that was not reviewed is renaming of the steps, which can be tested all together as a whole.

Well, it is a bit tedious - not for testing but doing the code review, because you have to wade through all the other changes to find (what you think might be) the relevant changes. It wasn't just the step renaming, there was the issue with reloading projects as well: https://github.com/mrc-ide/hint/pull/529#pullrequestreview-737105136

I guess it probably is too much to unfankle at this point (looks like you've made further changes on this branch anyway) - but can we agree in future to not jump the gun by merging the final sub-branches of an epic branch before they've been approved!? :pray:

**Comment by mwoodbri** [comment]
@carbowizzy Some guidance would be really helpful here:
- Is this branch is an epic branch or a feature branch? Or both??
  - Ticket mrc-2518 isn't an epic, but this branch seem to incorporate 3 other branches. Does it contain any changes not included in those branches?
- Have the concerns raised on mrc-2566 been addressed in this branch? Was that branch merged by accident?
- It's not clear to me how I should be testing this. Should the app still be fully functional with these changes applied? Where exactly is the mock-up for how it should look? I've checked the ticket mrc-2518 but it just has a Word document attached, and the description says "This ticket is just to do an investigation".

Sorry - I may be a bit behind, but it's hard to review PRs where the context isn't made explicit in the description.

**Comment by carbowizzy** [comment]
> @carbowizzy Some guidance would be really helpful here:
> 
> * Is this branch is an epic branch or a feature branch? Or both??
>   
>   * Ticket [mrc-2518](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2518) isn't an epic, but this branch seem to incorporate 3 other branches. Does it contain any changes not included in those branches?
> * Have the concerns raised on [mrc-2566](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2566) been addressed in this branch? Was that branch merged by accident?
> * It's not clear to me how I should be testing this. Should the app still be fully functional with these changes applied? Where exactly is the mock-up for how it should look? I've checked the ticket [mrc-2518](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2518) but it just has a Word document attached, and the description says "This ticket is just to do an investigation".
> 
> Sorry - I may be a bit behind, but it's hard to review PRs where the context isn't made explicit in the description.

I have updated the description, most of the changes are small bits here and there.

**Comment by carbowizzy** [comment]
> > > review
> > 
> > 
> > It was but I am struggling to revample the [mrc-2566](https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2566) properly. I think it won't be so tedious reviewing this epic since we have had some of them reviewed. The only bit that was not reviewed is renaming of the steps, which can be tested all together as a whole.
> 
> Well, it is a bit tedious - not for testing but doing the code review, because you have to wade through all the other changes to find (what you think might be) the relevant changes. It wasn't just the step renaming, there was the issue with reloading projects as well: [#529 (review)](https://github.com/mrc-ide/hint/pull/529#pullrequestreview-737105136)
> 
> I guess it probably is too much to unfankle at this point (looks like you've made further changes on this branch anyway) - but can we agree in future to not jump the gun by merging the final sub-branches of an epic branch before they've been approved!? 🙏

Absolutely, since the branch was the final sub-branch, I felt it was unnecessary to review twice but to combine effort.

**Review by EmmaLRussell — APPROVED** [review]
This all seems to work, and as far as I can tell, no significant code differences from previous branches. Have tested with loading both projects and saved files which had the old step names, which both work fine. Conflicts need fixing.

**Review by mwoodbri — COMMENTED** [review]
Looks good. Appear to be some persistent test failures though?

**Review by mwoodbri — COMMENTED** [review]
Still looks good, but there also still seems to be a persistent test failure

**Comment by carbowizzy** [comment]
> Still looks good, but there also still seems to be a persistent test failure

ADR failure...

**Review by mwoodbri — APPROVED** [review]

**Pull request merged**
