### PR TITLE
Vue 3 Upgrade

### PR DESCRIPTION
**Pull request by M-Kusumgar**
## Description

The start of the Vue 3 upgrade

## Guide

Please click on each commit in order and see the files changed and my comments underneath (read the comments **first**). These are a couple of commits I did at the start. I will slowly push more once these have been reviewed. I have 149 changes lined up (and still more to come) but most of them are of the same flavour so should hopefully be alright!

From this point I will branch out from this branch and do sub PRs so you can see the changes in a more isolated way.

## Checklist

- [ No] I have incremented version number, or version needs no increment
- [ No] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Comment by LekanAnni** [comment]
Hey @M-Kusumgar I think you need to resolve merge conflicts before review.

**Review by LekanAnni — CHANGES_REQUESTED** [review]
I have not looked at the code, I think you need to resolve merge conflicts.

**Comment by M-Kusumgar** [comment]
just merged main into here, conflicts should be resolved

**Review by EmmaLRussell — COMMENTED** [review]
Just a few comments on the changes, following on from what I wrote earlier. This looks like a great start as a base for the epic. 

So you're abolishing the `app` folder under static and putting `src` and `tests` directly under `static`? And `scss` is included under `src`? This is just to simplify the folder structure, or was there another reason? I don't disagree with it (vaguely remember us chatting about it?), though I guess it's debatable that a more nested structure would keep script and config away from the code. Could really have gone in another ticket, this is mammoth enough as it is, but happy to leave it in! 

> hell begins now

🤘

**Review by hillalex — COMMENTED** [review]
Similar qs to Emma, but looks good (and easy to follow commits, thanks for organising this way)

**Comment by M-Kusumgar** [comment]
I have taken the comments from here and quickly redid the configs stuff! Please ignore this PR, I wont close it because there are some relevant comments here but for future work on Vue 3 upgrade please refer to #822

**Pull request closed without merging**
