### PR TITLE
mrc-3194 Prevent spamming download and meta endpoints after download generate completes

### PR DESCRIPTION
**Pull request by Nicolas-Dolan**
## Description

To reproduce the bug, progress to save results step. While download files are still generating (reloading the page will trigger a regeneration), navigate to the the project history page and create a new project. Observe in the console that `metadata` and `downloadResults` endpoints are being spammed:
image
This fix prevents this and returns normal behaviour, although it does not fix the bug outlined in mrc-3239.
image

**Tip:** to avoid having to go through the stepper every time you want to reproduce the bug, proceed to the final step once and then clone the project multiple times before triggering the bug. The clones should not be affected by the state bug outlined in mrc-3239.

**Update:** PR now also includes fix for state wiping bug outlined in mrc-3239

## Type of version change
Patches

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Comment by LekanAnni** [comment]
https://user-images.githubusercontent.com/4240748/169860311-376af78e-acec-4973-9f2f-a31db8dc35ae.mov

**Comment by LekanAnni** [comment]
Download pollings are not showing but the state us still destroyed.

**Comment by Nicolas-Dolan** [comment]
> As discussed, a better solution would be to call `DownloadResultsMutation.ResetIds` from createProject action.

This pr was already doing that just without the `preparing` checking if statement beforehand. I'm still getting the bug though. Were there any other changes? Had we changed the resetId mutation?

**Comment by Nicolas-Dolan** [comment]
PR now also includes fix for state wiping bug outlined in mrc-3239

**Review by LekanAnni — CHANGES_REQUESTED** [review]
I can't seem to reproduce the bug anymore, looks like the fix works. 

I however noticed that when a tester follows the steps to reproduce the bug, upon creating a new project, the state from an old project such as current step and warnings appear for the new project before resetting itself to the actual project state. It would be nice if you could ensure a new project does not initially display old state.

**Comment by Nicolas-Dolan** [comment]
> I can't seem to reproduce the bug anymore, looks like the fix works.
> 
> I however noticed that when a tester follows the steps to reproduce the bug, upon creating a new project, the state from an old project such as current step and warnings appear for the new project before resetting itself to the actual project state. It would be nice if you could ensure a new project does not initially display an old state.

I haven't been able to observe that testing it myself. So when you created a new project, it initially opens on a later step and visible warnings or are you just observing the state in the console?

**Comment by LekanAnni** [comment]
> > I can't seem to reproduce the bug anymore, looks like the fix works.
> > I however noticed that when a tester follows the steps to reproduce the bug, upon creating a new project, the state from an old project such as current step and warnings appear for the new project before resetting itself to the actual project state. It would be nice if you could ensure a new project does not initially display an old state.
> 
> I haven't been able to observe that testing it myself. So when you created a new project, it initially opens on a later step and visible warnings or are you just observing the state in the console?

Warnings are displayed for a second or 2 on the page not in console.

**Comment by Nicolas-Dolan** [comment]
> > > I can't seem to reproduce the bug anymore, looks like the fix works.
> > > I however noticed that when a tester follows the steps to reproduce the bug, upon creating a new project, the state from an old project such as current step and warnings appear for the new project before resetting itself to the actual project state. It would be nice if you could ensure a new project does not initially display an old state.
> > 
> > 
> > I haven't been able to observe that testing it myself. So when you created a new project, it initially opens on a later step and visible warnings or are you just observing the state in the console?
> 
> Warnings are displayed for a second or 2 on the page not in console.

Weird, I can't see that at all. Maybe it's just happening a lot faster for me. I'll take a look

**Comment by EmmaLRussell** [comment]
> Warnings are displayed for a second or 2 on the page not in console.

I'm seeing this behaviour, but not on create project - I can see it when you reload an empty pre-existing project having been in a project on a step with warnings. That's happening for me on master, so I don't think it's just an issue for this branch. Would suggest fixing that in a separate ticket.

**Review by EmmaLRussell — APPROVED** [review]
Nice, this works for me.

However, we've still got the same issue with calibrate - i.e. if you browse to Projects and create w new project while calibration is still going on, you'll see that the calibrate status keeps getting spammed. It would be really good to get the state wipe fix in asap though, so I'd suggest addressing that in a separate ticket. And same for the stale warnings issue @LekanAnni mentioned. 

You can't seem get into the same pickle with Model Fit, because the model fit has a modal dialog that prevents you browsing to Projects while the fit it going on, and if you browse to /projects manually in the same tab that has the effect of clearing the intervals anyway.

**Review by LekanAnni — APPROVED** [review]
LGTM 👍 

If you could create a ticket to fix the stale state in my previous comment, I am happy for this to be merged.

**Pull request merged**
