### PR TITLE
mrc-2826 - Updating help documentation

### PR DESCRIPTION
**Pull request by Nicolas-Dolan**
## Description

Updates English and Portuguese documentation on the Basic steps link to new file (English for both). French will remain as is for now. Please check that the new file has no blank pages and that the date on the front page says 02 December 2021 (not 2022).

## Type of version change
Minor

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Comment by LekanAnni** [comment]
> ## Description
> Updates English and Portuguese documentation on the Basic steps link. I had to convert a Word document to PDF and then delete some blank pages. I've noticed two issues with the PDF: the contents in the navigation sidebar are messed up and the date on the front page is wrong. I'll try to get Rachel to generate a PDF for me when she is in tomorrow.
> 
> ## Type of version change
> Minor
> 
> ## Checklist
> * [x]  I have incremented version number, or version needs no increment
> * [x]  The build passed successfully, or failed because of ADR tests

404 error, have have only changed the name but not linked the file. Can you check the location of the resource file?

Screenshot 2021-12-03 at 09 32 43

**Review by LekanAnni — CHANGES_REQUESTED** [review]
404 error, see above screenshot.

ensure the file exists here /public/resources/Naomi-instructions-2021.pdf

**Comment by Nicolas-Dolan** [comment]
> 404 error, see above comment.

That's strange, it's working for me. Did you pull from the branch and then rebuild? Try restarting your dependencies and see if that fixes it.

**Comment by LekanAnni** [comment]
> > 404 error, see above comment.
> 
> That's strange, it's working for me. Did you pull from the branch and then rebuild? Try restarting your dependencies and see if that fixes it.

I did, I looked at the /public/resource for the file but it's not there.

**Review by LekanAnni — APPROVED** [review]
LGTM 👍

**Comment by Nicolas-Dolan** [comment]
Now updated to use the amended pdf from Rachel. Please check that the new file has no blank pages and that the date on the front page says 02 December 2021 (not 2022). @richfitz if you have time, could you also review, as we are short on reviewers?

**Review by richfitz — APPROVED** [review]
LGTM, did a check through and no missed occurrences of the old string. I've not spun up the app though.

**Review by LekanAnni — APPROVED** [review]
Great 👍 

Pdf is linkable and displays as expected. I believe Rachel already verified content of the pdf.

**Pull request merged**
