### PR TITLE
Mrc-2923 - Handle resource with missing download more gracefully

### PR DESCRIPTION
**Pull request by LekanAnni**
## Description
This PR checks if resource URL exists before importing its resource files. In some cases, resource will exists in ADR but without resource files, which causes the app to display errors.

## Type of version change
_Delete as appropriate_

Minor 

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by EmmaLRussell — CHANGES_REQUESTED** [review]
I can see how this would work but I think this approach adds quite a lot of boilerplate code to the component that's not ideal. I did think about changing this in the backend to just sidestep the error with trying to create a URL object with empty string - but then we would have to add code to return custom response in that situation. 

So I think the simplest thing to do would actually just be to change the relevant import actions eg [importPJNZ](https://github.com/mrc-ide/hint/blob/master/src/app/static/src/app/store/baseline/actions.ts#L129) to do nothing if `url` parameter is falsy  e.g. 
```
async importPJNZ(context, url) {
       if (url) {
          await uploadOrImportPJNZ(context, {url: "/adr/pjnz/", payload: qs.stringify({url})},
              getFilenameFromImportUrl(url));
        }
    },
```

**Review by r-ash — APPROVED** [review]
I've deployed this to dev and checked it has fixed the issue, thanks!

**Comment by LekanAnni** [comment]
> I can see how this would work but I think this approach adds quite a lot of boilerplate code to the component that's not ideal. I did think about changing this in the backend to just sidestep the error with trying to create a URL object with empty string - but then we would have to add code to return custom response in that situation.
> 
> So I think the simplest thing to do would actually just be to change the relevant import actions eg [importPJNZ](https://github.com/mrc-ide/hint/blob/master/src/app/static/src/app/store/baseline/actions.ts#L129) to do nothing if `url` parameter is falsy e.g.
> 
> ```
> async importPJNZ(context, url) {
>        if (url) {
>           await uploadOrImportPJNZ(context, {url: "/adr/pjnz/", payload: qs.stringify({url})},
>               getFilenameFromImportUrl(url));
>         }
>     },
> ```

I actually considered this option, it was my first thought but I didn't think it's okay to handle this logic in action. We have always checked parameters before passing it down to action endpoint instead of checking in action.

**Comment by EmmaLRussell** [comment]
>We have always checked parameters before passing it down to action endpoint instead of checking in action. It also makes testing easier.

It's actually a mixture - we have plenty of examples of actions which make decisions based on state/input parameters e.g. [here](https://github.com/mrc-ide/hint/blob/master/src/app/static/src/app/store/baseline/actions.ts#L102) and [here](https://github.com/mrc-ide/hint/blob/master/src/app/static/src/app/store/adrUpload/actions.ts#L23). I think in general it's better for the components to just be dealing with user interactions and leave any other decisions to do with state to the actions. 

Surely putting the check in the action would be much easier to test as the action test would just need to provide the truthy/falsy url parameter in the action parameter and then check if mockAxios has been called or not. The test you've added for the component check is doing masses of setup - it's almost 100 lines long! - plus you've had to add all those additional Vue.nextTicks...

**Review by EmmaLRussell — APPROVED** [review]
Could check mockAxios as well as commit, but I think as a minimal test this is fine since all the import functions do an initial commit.

**Review by Nicolas-Dolan — APPROVED** [review]

**Pull request merged**
