### PR TITLE
mrc-583: Add partner logos to login screen

### PR DESCRIPTION
**Pull request by r-ash**
This has been a long time coming

This PR will

* Add logos with links to web pages for partners

Still a question of whether we should add Fjelltopp & Avenir here - I can ask Jeff & Mary and make that change.

The test is bit odd I feel - let me know if there is a better way to check that.

### CODE REVIEW

**Comment by EmmaLRussell** [comment]
Do you what's going om with the Travis build failure?

**Comment by EmmaLRussell** [comment]
Need to commit the images too? :)

**Comment by hillalex** [comment]
Looks like one more typo in the tests @r-ash

**Comment by hillalex** [comment]
Sorry @r-ash still need to fix that test

**Pull request merged**
