### PR TITLE
mrc-2754 Rename baseline and surveyAndProgram components

### PR DESCRIPTION
**Pull request by Nicolas-Dolan**
## Description

Renamed as `UploadInputs` and `ReviewInputs`, respectively. Renaming and restructuring of modules will be covered in another ticket mrc-2759 (or not?).

## Type of version change
Patches

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by hillalex — COMMENTED** [review]
Fab, thanks. Version # has already moved on (what a faff this manual versioning is) so now needs to be `1.68.2` I think.

**Review by LekanAnni — CHANGES_REQUESTED** [review]
Looking good.

Working but there there's a bug in stepper.

To reproduce:
- Create a new project 
- load datasets
- click step 2 
- click step 1 
- check console for error

**Comment by hillalex** [comment]
> Looking good.
> 
> Working but there there's a bug in stepper.
> 
> To reproduce:
> 
> * Create a new project
> * load datasets
> * click step 2
> * click step 1
> * check console for error

Was the error: ` Error in render: "TypeError: Cannot read properties of undefined (reading 'max')"`?

It took me a while to replicate this and I was finally able to replicate it on master. 

It took me a while to replicate this and for me the required steps were:

* Select Antarctica 2022-1 owned by Naomi Development Team
* Navigate to step 2 and notice that there are 4 available indicators: HIV prevalence, ART coverage, Proportion recently infected and Viral load suppression
* Navigate back to step 1 and select Antarctica-2022-1-2 owned by Imperial College London
* Navigate to step 2 and notice there are 2 available indicators: ANC HIV prelanence, ANC prior ART coverage

The choropleth has remembered the previous indicator selection but it doesn't exist in the new dataset, hence the error. This is unrelated to this changeset.

However, something very weird is going on with the ADR data import because this didn't always happen; sometimes the second import appeared to re-import the first file. I wonder if related to the two datasets having the same name? Needs further investigation as a high priority in case this is a more serious bug.

**Comment by hillalex** [comment]
> > Looking good.
> > Working but there there's a bug in stepper.
> > To reproduce:
> > 
> > * Create a new project
> > * load datasets
> > * click step 2
> > * click step 1
> > * check console for error
> 
> Was the error: ` Error in render: "TypeError: Cannot read properties of undefined (reading 'max')"`?
> 
> It took me a while to replicate this and I was finally able to replicate it on master.
> 
> It took me a while to replicate this and for me the required steps were:
> 
> * Select Antarctica 2022-1 owned by Naomi Development Team
> * Navigate to step 2 and notice that there are 4 available indicators: HIV prevalence, ART coverage, Proportion recently infected and Viral load suppression
> * Navigate back to step 1 and select Antarctica-2022-1-2 owned by Imperial College London
> * Navigate to step 2 and notice there are 2 available indicators: ANC HIV prelanence, ANC prior ART coverage
> 
> The choropleth has remembered the previous indicator selection but it doesn't exist in the new dataset, hence the error. This is unrelated to this changeset.
> 
> However, something very weird is going on with the ADR data import because this didn't always happen; sometimes the second import appeared to re-import the first file. I wonder if related to the two datasets having the same name? Needs further investigation as a high priority in case this is a more serious bug.

However should not hold up merging this PR.

**Comment by LekanAnni** [comment]
> However should not hold up merging this PR.

Did you create a ticket for this already ?

**Review by LekanAnni — APPROVED** [review]

**Comment by hillalex** [comment]
> > Needs further investigation as a high priority in case this is a more serious bug.
> 
> Did you create a ticket for this already ?

I haven't, would you like to go ahead and create one?

**Comment by LekanAnni** [comment]
bug fix:  https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-2771

**Review by hillalex — APPROVED** [review]

**Pull request merged**
