### PR TITLE
Add staging deploy triggered build

### PR DESCRIPTION
**Pull request by r-ash**
## Description

Triggers an automatic deploy on new staging server when a branch is merged into master

## Type of version change

None

## Checklist

- [x] I have incremented version number, or version needs no increment
- [ ] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by LekanAnni — CHANGES_REQUESTED** [review]
Looking good, Perhaps we could wait for master build to succeed before triggering deployment.

**Comment by hillalex** [comment]
> Looking good, Perhaps we could wait for master build to succeed before triggering deployment.

I think the `wait` in the buildkite config ensures that, is that right @r-ash ?

**Comment by LekanAnni** [comment]
> Yep that's right, will only trigger the build if all the tests pass

Oh ok, my understanding was deployment will trigger even when build failed as long as it the process is complete.

**Review by hillalex — APPROVED** [review]

**Review by LekanAnni — APPROVED** [review]
LGTM

**Pull request merged**
