### PR TITLE
mrc-3191 Add Comparison download ID to generateErrorReport action

### PR DESCRIPTION
**Pull request by LekanAnni**
## Description

This PR adds comparison download ID to error generation report.

How to test:
1. Load app to the final download step
2. From Online support -> click troubleshooting request and file the form
3. Check teams "Naomi support" channel for the generated error report

## Type of version change
_Delete as appropriate_

Major - Minor - Patches - None

## Checklist

- [x] I have incremented version number, or version needs no increment
- [x] The build passed successfully, or failed because of ADR tests

### CODE REVIEW

**Review by r-ash — COMMENTED** [review]
Changes here look good, have you been able to test this end to end? I can't see a log in the naomi support channel with a comparison ID set, but maybe it is just lost in the history.

I think it worth putting the MS power automate flow code into version control, maybe even just in this repo somewhere? With a README with some link to edit the flow?

**Comment by LekanAnni** [comment]
> I think it worth putting the MS power automate flow code into version control, maybe even just in this repo somewhere? With a README with some link to edit the flow?

As mentioned, this is essential. I have added a ticket for it https://mrc-ide.myjetbrains.com/youtrack/issue/mrc-3987/Create-a-repository-for-MS-power-automate-workflow-steps

**Comment by LekanAnni** [comment]
> Changes here look good, have you been able to test this end to end? I can't see a log in the naomi support channel with a comparison ID set, but maybe it is just lost in the history.

You should be able to test this but yeah it does work.

**Review by EmmaLRussell — APPROVED** [review]
LGTM - just ran it up locally, so request didn't go through to the Teams channel, but I could see comparison download id was added to the request payload.

**Review by r-ash — APPROVED** [review]
Nice, have checked this works end to end by deploying on preview and can see that comparison report ID coming through

**Pull request merged**
